# Numpy

In [1]:
import numpy as np

# Basic

In [14]:
# initializing 1D array
a = np.array([1,2,3])       #By deafult numpy make an array of int32 
b = np.array([1,2,3], dtype="int16")  

# initializing 2D array
c = np.array([[1,2,3],[4,5,6]])

# initializing 3D array
d = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])    #Array of float
e = np.array([[[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]])  #[] represents the dimension of an array

In [22]:
print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]


In [15]:
#Get Dimension
print('a = ',a.ndim)
print('b = ',b.ndim)
print('c = ',c.ndim)
print('d = ',d.ndim)
print('e = ',e.ndim)

a =  1
b =  1
c =  2
d =  2
e =  3


In [16]:
#Get Shaoe
print('a = ',a.shape)
print('b = ',b.shape)
print('c = ',c.shape)
print('d = ',d.shape)
print('e = ',e.shape)

a =  (3,)
b =  (3,)
c =  (2, 3)
d =  (3, 3)
e =  (1, 3, 3)


In [17]:
#Get Type
print('a = ',a.dtype)
print('b = ',b.dtype)
print('c = ',c.dtype)
print('d = ',d.dtype)
print('e = ',e.dtype)

a =  int32
b =  int16
c =  int32
d =  float64
e =  float64


In [18]:
#Get Size
print('a = ',a.size)
print('b = ',b.size)
print('c = ',c.size)
print('d = ',d.size)
print('e = ',e.size)    #Tells the total number of elements in an array

a =  3
b =  3
c =  6
d =  9
e =  9


In [19]:
#Get size of elements
print('a = ',a.itemsize)
print('b = ',b.itemsize)
print('c = ',c.itemsize)
print('d = ',d.itemsize)
print('e = ',e.itemsize)   #Tells the size of each single element in an array in bytes

a =  4
b =  2
c =  4
d =  8
e =  8


In [20]:
#Get Total size
print('a = ',a.nbytes)   #We can also use a.size * a.itemsize  3*4=12
print('b = ',b.nbytes)
print('c = ',c.nbytes)
print('d = ',d.nbytes)
print('e = ',e.nbytes)    #Tells the total size of an array in bytes

a =  12
b =  6
c =  24
d =  72
e =  72


# Accessing / Changing specific elements,rows,columns etc

In [25]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12]])
print(a)                          

[list([1, 2, 3, 4, 5, 6, 7, 8]) list([9, 10, 11, 12])]


In [59]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [28]:
#Getting specific elements [row,column]
print(a[1,2])
print(a[0,1:5])

11
[2 3 4 5]


In [33]:
#Getting specific row
print(a[0,:])
print(a[1,2:])
print(a[1,1::2])

[1 2 3 4 5 6 7 8]
[11 12 13 14 15 16]
[10 12 14 16]


In [44]:
#Getting specific column
print(a[:,2])
print(b[:,1])
print(b[1:,0])
print(b[:,1:2])

[ 3 11]
[2 5 8]
[4 7]
[[2]
 [5]
 [8]]


In [58]:
#Using Negative indexing
print(a[1,-2])
print(a[0,-2:])
print(a[1,-5:7])
print(b[-2])

15
[7 8]
[12 13 14 15]
[4 5 6]


In [62]:
c = np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [63]:
print(c[0,1,0])

2


In [66]:
#Changing elements 
a[1,2:5] = 5
print(a)
a[1,2:5] = [20,21,22]
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10  5  5  5 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 20 21 22 14 15 16]]


# Initializing Different Type of Arrays

In [68]:
#Array of all zeros
a = np.zeros(3)
a

array([0., 0., 0.])

In [71]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
a = np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
a = np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [76]:
#Arrays of all ones
b = np.ones(3)
b

array([1., 1., 1.])

In [77]:
b = np.ones((2,4) , dtype="int16")       #we can give our required data type
b
print(b.dtype)
print(type(b))

int16
<class 'numpy.ndarray'>


In [78]:
#Any other number
c = np.full([2,3], 10)           #we can use tuple for shape (2,3)
c

array([[10, 10, 10],
       [10, 10, 10]])

In [79]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)
x

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
c = np.full(x.shape, 40)
c

array([[40, 40, 40],
       [40, 40, 40]])

In [85]:
c = np.full(x,20)           #we can do it by full_like function
c

TypeError: only integer scalar arrays can be converted to a scalar index

In [86]:
c =np.full_like(x, 20)        #function takes the shape of x by itself
c

array([[20, 20, 20],
       [20, 20, 20]])

In [82]:
#Random decimal number
d = np.random.rand(2,3)
d

array([[0.18327701, 0.72377701, 0.18900177],
       [0.28330577, 0.86485881, 0.4687825 ]])

In [88]:
#Random integer numbers
d = np.random.randint(3,7)
d

6

In [90]:
d = np.random.randint(5,size=(3,7))
d                                            #(range,size)

array([[4, 2, 4, 2, 2, 0, 3],
       [2, 3, 0, 4, 2, 4, 0],
       [3, 1, 4, 3, 1, 4, 4]])

In [93]:
d = np.random.randint(3,5,size=(3,7))
d    #range 3 to 5 but 5 is not inclusive 

array([[3, 3, 3, 3, 3, 4, 4],
       [4, 3, 4, 3, 3, 4, 4],
       [3, 4, 3, 4, 4, 3, 4]])

In [94]:
d = np.random.randint(-1,5,size=(3,7))
d    

array([[ 2,  4,  4, -1, -1,  2,  2],
       [ 2,  1,  3,  3,  0,  0, -1],
       [ 4,  2,  4,  3,  0,  0,  3]])

In [95]:
#Identity Matrix
i = np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
#Repeating an Array
x = np.array([1,2,3])
d = np.repeat(x,3)
d

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [99]:
d = np.repeat(x,3,axis=0)
d

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [100]:
d = np.repeat(x,3,axis=2)
d

AxisError: axis 2 is out of bounds for array of dimension 1

In [102]:
x = np.array([[1,2,3]])
d = np.repeat(x,3,axis=1)
d

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [103]:
d = np.repeat(x,3,axis=0)
d

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [104]:
#Placing one matrix into another
m1 = np.zeros((5,5))
print(m1)
m2 = np.ones((3,3))
print(m2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [105]:
m2[1,1] = 5
m2

array([[1., 1., 1.],
       [1., 5., 1.],
       [1., 1., 1.]])

In [106]:
m1[1:4,1:4] = m2
m1

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 5., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# Mathematics on Array

In [107]:
#Arithmetic Operations
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [108]:
a+2

array([3, 4, 5, 6])

In [109]:
a*3

array([ 3,  6,  9, 12])

In [110]:
a-2

array([-1,  0,  1,  2])

In [111]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [112]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [113]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [114]:
b = np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [115]:
a+b

array([ 6,  8, 10, 12])

In [116]:
a*b

array([ 5, 12, 21, 32])

In [117]:
#Trignometric Operations
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [118]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [119]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [123]:
np.cot(a)

AttributeError: module 'numpy' has no attribute 'cot'

In [124]:
np.cos(a)/np.sin(a)

array([ 0.64209262, -0.45765755, -7.01525255,  0.86369115])

In [125]:
#Linear Algebric Operations
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [126]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [131]:
np.matmul(a,b)     #Matrix Multiplication

array([[6., 6.],
       [6., 6.]])

In [132]:
x = np.identity(2)     
np.linalg.det(x)                    #Determinant

1.0

In [133]:
#Statistics Operations
s = np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
np.min(s)

1

In [135]:
np.min(s, axis=1)    #Min of both rows

array([1, 4])

In [136]:
np.max(s)

6

In [137]:
np.max(s,axis=1)

array([3, 6])

In [138]:
np.sum(s)

21

In [139]:
np.sum(s,axis=1)     #sum of both roms

array([ 6, 15])

In [140]:
np.sum(s,axis=0)        #sum of all columns

array([5, 7, 9])

# Reorganizing Arrays

In [141]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [144]:
a2 = a1.reshape((4,2))
a2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [145]:
#Vertically Stacking Vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [146]:
np.vstack([v1,v2,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [149]:
#Horizontally Stacking Vectors
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

# Data Loading From File

In [155]:
filedata = np.genfromtxt("data.txt",delimiter=',')
print(filedata)

OSError: data.txt not found.

# Boolean Masking and Advanced Indexing

In [156]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [157]:
a>50

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [161]:
np.any(a>50,axis=0)

array([False,  True,  True,  True])

In [162]:
np.all(a>50,axis=0)

array([False, False, False, False])

In [163]:
((a>30)&(a<50))

array([[False, False, False,  True],
       [False, False, False, False]])

In [165]:
(~(a>30)&(a<50))

array([[ True,  True,  True, False],
       [False, False, False, False]])

In [158]:
a[a>50]

array([60, 70, 80])

In [160]:
#Indexing with a list
b = np.array([1,2,3,4,5,6,7,8,9])
b[[1,2,8]]

array([2, 3, 9])